# Generated by Django 2.1.7 on 2019-03-15 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('C', 'classic'), ('S', 'sad'), ('h', 'happy'), ('m', 'melody'), ('d', 'devotional')], max_length=1)),
                ('song', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('director', models.CharField(blank=True, max_length=50)),
                ('photo', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('C', 'classic'), ('S', 'sad'), ('h', 'happy'), ('m', 'melody'), ('d', 'devotional')], max_length=1)),
                ('song', models.FileField(blank=True, upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.movie')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.movie'),
        ),
    ]
