# Generated by Django 2.1.7 on 2019-03-18 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Movie'),
        ),
        migrations.AlterField(
            model_name='video',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Movie'),
        ),
    ]
